### ISSUE TITLE
Flow type error when upgrading to version 1.0.4

### ISSUE THREAD

**Issue by jrzimmerman** [fusionjs/fusion-plugin-font-loader-react#100]
When upgrading to `fusion-plugin-font-loader-react` from 1.0.3 to `1.0.4` I get the following flow error.
I am using `flow-bin` `^0.79.0`
```
yarn flow
yarn run v1.9.4
$ flow check
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/fusion-plugin-font-loader-react/src/font-loader.js:37:10

Missing type annotation for R.

     34│   // $FlowFixMe
     35│   testDivs.forEach(div => (div.style.fontFamily = `${font}, ${div.testFont}`));
     36│   const waitUntil = Date.now() + timeout;
     37│   return new Promise(resolve => {
     38│     (function monitorWidth(delay) {
     39│       setTimeout(function() {
     40│         if (Date.now() >= waitUntil || hasFontLoaded(testDivs)) {
     41│           resolve();
     42│           cleanup(testDivs);
     43│         } else {
     44│           monitorWidth(Math.max(delay * 1.5, 500));
     45│         }
     46│       }, delay);
     47│     })(10);
     48│   });
     49│ }
     50│
     51│ function hasFontLoaded(testDivs) {

```

### Type of issue

This is a bug.

### Description

I would like the flow type check to pass.

### Current behavior

The flow type check does not pass for flow 0.79.0.

### Expected behavior

The flow type check should pass for flow 0.79.0.

### Steps to reproduce

1. Run a flow type check using flow-bin 0.79.0

### Your environment

* fusion-plugin-font-loader-react version: 1.0.4

* Node.js version (`node --version`): 8.11.4

* npm version (`npm --version`): 5.6.0

* Operating System: mac

**Comment by KevinGrandon** [comment]
Thanks for reporting this issue. Seems like we're also seeing this fail here: https://github.com/fusionjs/fusion-plugin-font-loader-react/pull/99

We'll look into this.
